services:
  book-storage:
    build: .
    networks:
      - my-net
    ports:
      - 80:3000
    environment:
      - SERVER_PORT=3000
      - COUNTER_URL=http://counter:3000
  counter:
    image: fichca/counter
    networks:
      - my-net
    ports:
      - 81:3000
    environment:
      - SERVER_PORT=3000

networks:
  my-net:
    driver: bridge